#!/usr/bin/python

import urllib.request
import extraction as b
import os
import sys
import time
import threading
import math

# forder and link setup here and for text and data extraction see beautify.py


folder_name = "STORAGE/Against the gods/Chapter_upto/"
links_folder = "STORAGE/Against the gods/chapterLinks_ATG.txt"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"}
counter = 0

def fetch_and_save(url):
    # chapter_name = url.split('/')[-1]
    
    # # for nine start 
    # chapter_name = chapter_name[1:]

    chapter_name = False

    try:
        req = urllib.request.Request(url, headers=headers)
        response = urllib.request.urlopen(req)
        data = response.read()
        text_data = data.decode("utf-8")
        chapter_name = b.non_rawing(chapter_name,text_data,folder_name)

        print(chapter_name,"saved successfully")

    except urllib.error.URLError as e:
        print(f"Failed to fetch data. Error: {e}")
        sys.exit()



def indi_thread_call(links:list):
    global counter
    # startx = 3767
    # endx = 4138
    enumx = 0

    
    thread_name = threading.current_thread().name

    # for nine star
    # startx = startx - 2

    for l in links:
        counter += 1
        enumx = enumx + 1

        if enumx % 15 == 0:
            time.sleep(30)

        print(f"\nTotal_counter: {counter} Thread no:{thread_name} saving chapter: ",enumx)
        fetch_and_save(l.strip())   


with open(links_folder,'r') as file:
    
    if os.path.exists(folder_name):
        print("Directory exists.")
    else:
        print("Directory not found, creating one...")
        
        try:
            os.makedirs(folder_name)
            print("Directory created successfully.")
        except OSError as e:
            print(f"Error: {e}")
    
    links = file.readlines()
    each_slice = math.floor(len(links)/15)
    
    l1 = links[:each_slice-1]
    l2 = links[each_slice-1:(each_slice)*2-1]
    l3 = links[each_slice*2-1:each_slice*3-1]
    l4 = links[each_slice*3-1:each_slice*4-1]
    l5 = links[each_slice*4-1:each_slice*5-1]
    l6 = links[each_slice*5-1:each_slice*6-1]
    l7 = links[each_slice*6-1:each_slice*7-1]
    l8 = links[each_slice*7-1:each_slice*8-1]
    l9 = links[each_slice*8-1:each_slice*9-1]
    l10 = links[each_slice*9-1:each_slice*10-1]
    l11 = links[each_slice*10-1:each_slice*11-1]
    l12 = links[each_slice*11-1:each_slice*12-1]
    l13 = links[each_slice*12-1:each_slice*13-1]
    l14 = links[each_slice*13-1:each_slice*14-1]
    l15 = links[each_slice*14-1:]

    T1 = threading.Thread(name="t1",target=indi_thread_call,args=(l1,))
    T2 = threading.Thread(name="t2",target=indi_thread_call,args=(l2,))
    T3 = threading.Thread(name="t3",target=indi_thread_call,args=(l3,))
    T4 = threading.Thread(name="t4",target=indi_thread_call,args=(l4,))
    T5 = threading.Thread(name="t5",target=indi_thread_call,args=(l5,))
    T6 = threading.Thread(name="t6",target=indi_thread_call,args=(l6,))
    T7 = threading.Thread(name="t7",target=indi_thread_call,args=(l7,))
    T8 = threading.Thread(name="t8",target=indi_thread_call,args=(l8,))
    T9 = threading.Thread(name="t9",target=indi_thread_call,args=(l9,))
    T10 = threading.Thread(name="t10",target=indi_thread_call,args=(l10,))
    T11 = threading.Thread(name="t11",target=indi_thread_call,args=(l11,))
    T12 = threading.Thread(name="t12",target=indi_thread_call,args=(l12,))
    T13 = threading.Thread(name="t13",target=indi_thread_call,args=(l13,))
    T14 = threading.Thread(name="t14",target=indi_thread_call,args=(l14,))
    T15 = threading.Thread(name="t15",target=indi_thread_call,args=(l15,))


    T1.start()
    T2.start()
    T3.start()
    T4.start()
    T5.start()
    T6.start()
    T7.start()
    T8.start()
    T9.start()
    T10.start()
    T11.start()
    T12.start()
    T13.start()
    T14.start()
    T15.start()

    T1.join()
    T2.join()
    T3.join()
    T4.join()
    T5.join()
    T6.join()
    T7.join()
    T8.join()
    T9.join()
    T10.join()
    T11.join()
    T12.join()
    T13.join()
    T14.join()
    T15.join()
